// <auto-generated />
using MagicCarpetWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MagicCarpetWebApp.Migrations
{
    [DbContext(typeof(MagicCarpetWebAppContext))]
    [Migration("20180619044913_ConcertLocations2")]
    partial class ConcertLocations2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MagicCarpetWebApp.Models.ConcertInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<Guid>("LocationId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("ConcertInfoes");
                });

            modelBuilder.Entity("MagicCarpetWebApp.Models.ConcertLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Station");

                    b.HasKey("Id");

                    b.ToTable("ConcertLocations");
                });

            modelBuilder.Entity("MagicCarpetWebApp.Models.ConcertInfo", b =>
                {
                    b.HasOne("MagicCarpetWebApp.Models.ConcertLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
